# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 26f427800cea7444fcb4428ecd705b8b513ab9f4f8b877f2cde7a64ce2dd76825e0c6755e2db2e440cb91c7ed2b3d3b0987ca1138bf132ecfeb8507f27b29b02

test:
  secret_key_base: 9c1db5ea82ee2a9e4d00e236a79e5801d619bcd44530826e30367a2e529f45586f51755210bae3a8c07534988cfd818dfde7615192383818c117b99e5170ad68

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
